// Generated by npm run compile from src/webview/main.ts. Do not edit directly.
"use strict";
(() => {
  // src/webview/analysis/charts.ts
  function createAnalysis(elements, state) {
    const SVG_NS = "http://www.w3.org/2000/svg";
    function svgEl(tag, attrs = {}) {
      const el = document.createElementNS(SVG_NS, tag);
      for (const [key, value] of Object.entries(attrs))
        el.setAttribute(key, String(value));
      return el;
    }
    function timeAxisFormatter(spanMs) {
      const options = { hour: "2-digit", minute: "2-digit", hour12: false };
      if (spanMs !== void 0 && spanMs < 3 * 60 * 1e3)
        options.second = "2-digit";
      if (state.displayTimezone === "utc")
        options.timeZone = "UTC";
      else if (state.displayTimezone && state.displayTimezone !== "local")
        options.timeZone = state.displayTimezone;
      try {
        return new Intl.DateTimeFormat(void 0, options);
      } catch {
        return null;
      }
    }
    function bucketTime(range, bucketCount, index) {
      if (range?.from === void 0 || range?.to === void 0 || !bucketCount)
        return void 0;
      const bucketSize = Math.max(1, (range.to - range.from) / bucketCount);
      return range.from + index * bucketSize;
    }
    function formatClock(ms, range) {
      const span = range?.from !== void 0 && range?.to !== void 0 ? range.to - range.from : void 0;
      const formatter = timeAxisFormatter(span);
      return formatter ? formatter.format(ms) : new Date(ms).toLocaleTimeString();
    }
    function chartLegend(items) {
      const legend = document.createElement("div");
      legend.className = "chart-legend";
      for (const item of items) {
        const entry = document.createElement("span");
        entry.className = "chart-legend-item";
        const swatch = document.createElement("span");
        swatch.className = `chart-legend-swatch ${item.className}`;
        entry.append(swatch, document.createTextNode(item.label));
        legend.append(entry);
      }
      return legend;
    }
    function emptySection(title) {
      const section = document.createElement("section");
      section.className = "chart-section chart-wide";
      const heading = document.createElement("h3");
      heading.textContent = title;
      section.append(heading);
      const empty = document.createElement("p");
      empty.textContent = "No data in this range.";
      section.append(empty);
      return section;
    }
    function xAxisTicks(svg, bucketCount, range, xFor, height) {
      const tickEvery = Math.max(1, Math.round(bucketCount / 6));
      for (let index = 0; index < bucketCount; index += tickEvery) {
        const time = bucketTime(range, bucketCount, index);
        if (time === void 0)
          continue;
        const label = svgEl("text", { x: xFor(index), y: height - 4, class: "chart-axis-label" });
        label.textContent = formatClock(time, range);
        svg.append(label);
      }
    }
    function volumeChart(rate, errors, range) {
      const bucketCount = rate.length;
      if (!bucketCount || !rate.some((item) => item.count > 0))
        return emptySection("Event volume");
      const section = document.createElement("section");
      section.className = "chart-section chart-wide";
      const heading = document.createElement("h3");
      heading.textContent = "Event volume";
      section.append(heading);
      const width = 720, height = 130, padTop = 10, padBottom = 18;
      const plotHeight = height - padTop - padBottom;
      const max = Math.max(1, ...rate.map((item) => item.count));
      const barGap = 2;
      const barWidth = Math.max(1, width / bucketCount - barGap);
      const svg = svgEl("svg", { viewBox: `0 0 ${width} ${height}`, class: "volume-chart", role: "img", "aria-label": "Event volume over time, with errors highlighted" });
      const maxLabel = svgEl("text", { x: 2, y: padTop, class: "chart-axis-label" });
      maxLabel.textContent = String(max);
      svg.append(maxLabel);
      rate.forEach((item, index) => {
        const errorCount = Math.min(item.count, errors[index]?.count ?? 0);
        const okCount = item.count - errorCount;
        const x = index * (barWidth + barGap);
        const okHeight = okCount / max * plotHeight;
        const errorHeight = errorCount / max * plotHeight;
        const anomalous = item.anomalous || errors[index]?.anomalous;
        const group = svgEl("g", { class: anomalous ? "volume-bar anomalous" : "volume-bar" });
        if (okHeight > 0)
          group.append(svgEl("rect", { x, width: barWidth, y: padTop + plotHeight - okHeight - errorHeight, height: okHeight, class: "volume-bar-ok" }));
        if (errorHeight > 0)
          group.append(svgEl("rect", { x, width: barWidth, y: padTop + plotHeight - errorHeight, height: Math.max(1, errorHeight), class: "volume-bar-error" }));
        const time = bucketTime(range, bucketCount, index);
        const title = svgEl("title");
        title.textContent = `${time !== void 0 ? formatClock(time, range) + "\n" : ""}${item.count} event${item.count === 1 ? "" : "s"}${errorCount ? `, ${errorCount} error${errorCount === 1 ? "" : "s"}` : ""}`;
        group.append(title);
        if (anomalous) {
          const dot = svgEl("circle", { cx: x + barWidth / 2, cy: padTop - 5, r: 2.5, class: "anomaly-marker" });
          const dotTitle = svgEl("title");
          dotTitle.textContent = "Unusually high compared to the rest of this range";
          dot.append(dotTitle);
          group.append(dot);
        }
        svg.append(group);
      });
      xAxisTicks(svg, bucketCount, range, (index) => index * (barWidth + barGap) + barWidth / 2, height);
      section.append(svg, chartLegend([{ className: "swatch-ok", label: "events" }, { className: "swatch-error", label: "errors" }]));
      return section;
    }
    function latencyChart(latency, range) {
      const bucketCount = latency.length;
      if (!bucketCount || !latency.some((item) => item.count > 0))
        return emptySection("Latency (ms)");
      const section = document.createElement("section");
      section.className = "chart-section chart-wide";
      const heading = document.createElement("h3");
      heading.textContent = "Latency (ms)";
      section.append(heading);
      const width = 720, height = 110, padTop = 10, padBottom = 18;
      const plotHeight = height - padTop - padBottom;
      const max = Math.max(1, ...latency.map((item) => Math.max(item.average, item.p95)));
      const step = bucketCount > 1 ? width / (bucketCount - 1) : 0;
      const svg = svgEl("svg", { viewBox: `0 0 ${width} ${height}`, class: "latency-chart", role: "img", "aria-label": "Average and p95 latency over time" });
      const maxLabel = svgEl("text", { x: 2, y: padTop, class: "chart-axis-label" });
      maxLabel.textContent = `${Math.round(max)}ms`;
      svg.append(maxLabel);
      const pathFor = (key) => {
        let d = "";
        let drawing = false;
        latency.forEach((item, index) => {
          const x = index * step;
          if (item.count === 0) {
            drawing = false;
            return;
          }
          const y = padTop + plotHeight - item[key] / max * plotHeight;
          d += drawing ? ` L ${x} ${y}` : ` M ${x} ${y}`;
          drawing = true;
        });
        return d.trim();
      };
      svg.append(svgEl("path", { d: pathFor("p95"), class: "latency-line latency-p95" }));
      svg.append(svgEl("path", { d: pathFor("average"), class: "latency-line latency-average" }));
      latency.forEach((item, index) => {
        if (item.count === 0)
          return;
        const x = index * step;
        const y = padTop + plotHeight - item.average / max * plotHeight;
        const dot = svgEl("circle", { cx: x, cy: y, r: item.anomalous ? 2.5 : 1.5, class: item.anomalous ? "latency-point anomalous" : "latency-point" });
        const time = bucketTime(range, bucketCount, index);
        const title = svgEl("title");
        title.textContent = `${time !== void 0 ? formatClock(time, range) + "\n" : ""}average ${Math.round(item.average)}ms, p95 ${Math.round(item.p95)}ms`;
        dot.append(title);
        svg.append(dot);
      });
      xAxisTicks(svg, bucketCount, range, (index) => index * step, height);
      section.append(svg, chartLegend([{ className: "swatch-average", label: "average" }, { className: "swatch-p95", label: "p95" }]));
      return section;
    }
    function sparkline(values) {
      const el = document.createElement("span");
      el.className = "sparkline";
      const max = Math.max(1, ...values);
      for (const value of values) {
        const bar = document.createElement("span");
        bar.className = "sparkline-bar";
        bar.style.height = `${Math.max(8, value / max * 100)}%`;
        el.append(bar);
      }
      return el;
    }
    function renderAnalysis(analysis) {
      if (!elements.analysisContent)
        return;
      const content = document.createDocumentFragment();
      content.append(volumeChart(analysis.rate ?? [], analysis.errors ?? [], analysis.range));
      content.append(latencyChart(analysis.latency ?? [], analysis.range));
      const status = document.createElement("section");
      const heading = document.createElement("h3");
      heading.textContent = "Status codes";
      status.append(heading);
      for (const item of analysis.statusCodes ?? []) {
        const p = document.createElement("p");
        p.textContent = `${item.code}: ${item.count}`;
        status.append(p);
      }
      content.append(status);
      const patterns = document.createElement("section");
      const patternHeading = document.createElement("h3");
      patternHeading.textContent = "Log patterns";
      patterns.append(patternHeading);
      for (const item of analysis.patterns ?? []) {
        const row = document.createElement("div");
        row.className = "pattern-row";
        const level = document.createElement("span");
        level.className = `level ${item.level}`;
        level.textContent = item.level;
        const text = document.createElement("span");
        text.className = "pattern-text";
        text.textContent = `${item.count} \xD7 ${item.message}`;
        text.title = item.message;
        row.append(level, text, sparkline(item.trend));
        patterns.append(row);
      }
      if (!patterns.querySelector(".pattern-row")) {
        const empty = document.createElement("p");
        empty.textContent = "No data in this range.";
        patterns.append(empty);
      }
      content.append(patterns);
      const groups = document.createElement("section");
      const groupHeading = document.createElement("h3");
      groupHeading.textContent = "Error groups";
      groups.append(groupHeading);
      for (const item of analysis.errorGroups ?? []) {
        const p = document.createElement("p");
        p.textContent = item.location ? `${item.count} \xD7 ${item.message} \u2014 ${item.location}` : `${item.count} \xD7 ${item.message}`;
        p.title = item.key;
        groups.append(p);
      }
      content.append(groups);
      elements.analysisContent.replaceChildren(content);
    }
    return { renderAnalysis };
  }

  // src/webview/bridge.ts
  var SnapshotBridge = class {
    constructor(api, state, query) {
      this.api = api;
      this.state = state;
      this.query = query;
    }
    api;
    state;
    query;
    pending = false;
    refreshRequested = false;
    updateRequested = false;
    request(force = false) {
      if (document.hidden) return;
      if (this.pending) {
        if (force) this.refreshRequested = true;
        else this.updateRequested = true;
        return;
      }
      this.pending = true;
      const state = this.state;
      this.api.postMessage({
        type: "snapshot",
        query: this.query(),
        serverId: state.selectedServer || void 0,
        levels: state.currentLevels(),
        page: state.page,
        before: state.before,
        sort: state.selectedSort || void 0,
        sortDirection: state.selectedSortDirection,
        columns: state.extraColumns,
        statsOnly: state.paused && !force
      });
    }
    received() {
      this.pending = false;
    }
    flush() {
      if (!this.refreshRequested && !this.updateRequested) return;
      const force = this.refreshRequested;
      this.refreshRequested = false;
      this.updateRequested = false;
      this.request(force);
    }
  };

  // src/webview/dom.ts
  function element(id) {
    const node = document.getElementById(id);
    if (!node) throw new Error(`Missing viewer element: ${id}`);
    return node;
  }
  function getElements() {
    return {
      logs: element("logs"),
      cellFilterMenu: element("cellFilterMenu"),
      cellFilterAction: element("cellFilterAction"),
      empty: element("empty"),
      search: element("search"),
      copyResults: element("copyResults"),
      fieldSuggestions: element("fieldSuggestions"),
      searchHelp: element("searchHelp"),
      searchHelpPanel: element("searchHelpPanel"),
      searchTools: element("searchTools"),
      searchToolsPanel: element("searchToolsPanel"),
      saveSearch: element("saveSearch"),
      savedSearchList: element("savedSearchList"),
      fieldsButton: element("fieldsButton"),
      fieldsPanel: element("fieldsPanel"),
      fieldsAll: element("fieldsAll"),
      fieldsNone: element("fieldsNone"),
      fieldList: element("fieldList"),
      analyze: element("analyze"),
      analysisDialog: element("analysisDialog"),
      analysisClose: element("analysisClose"),
      analysisStatus: element("analysisStatus"),
      analysisContent: element("analysisContent"),
      levelButton: element("levelButton"),
      levelMenu: element("levelMenu"),
      server: element("server"),
      follow: element("follow"),
      config: element("config"),
      manage: element("manage"),
      export: element("export"),
      import: element("import"),
      clear: element("clear"),
      stop: element("stop"),
      run: element("run"),
      status: element("status"),
      sessions: element("sessions"),
      command: element("command"),
      older: element("older"),
      newer: element("newer"),
      page: element("page"),
      mode: element("mode"),
      counts: element("counts"),
      contextDialog: element("contextDialog"),
      contextClose: element("contextClose"),
      contextExport: element("contextExport"),
      contextStatus: element("contextStatus"),
      contextLogs: element("contextLogs"),
      contextDetails: element("contextDetails"),
      saveSearchDialog: element("saveSearchDialog"),
      saveSearchForm: element("saveSearchForm"),
      saveSearchName: element("saveSearchName"),
      saveSearchCancel: element("saveSearchCancel")
    };
  }
  function cell(text, className) {
    const element2 = document.createElement("td");
    element2.textContent = String(text ?? "");
    if (className)
      element2.className = className;
    return element2;
  }
  function emptyMessage(text) {
    const message = document.createElement("p");
    message.className = "popover-empty";
    message.textContent = text;
    return message;
  }

  // src/webview/event-scope.ts
  var EventScope = class {
    abort = new AbortController();
    cleanups = [];
    frames = /* @__PURE__ */ new Set();
    listen(target, type, handler, options = {}) {
      if (target.isConnected === false) {
        target.addEventListener(type, ((event) => {
          if (!this.abort.signal.aborted) handler(event);
        }), options);
      } else target.addEventListener(type, handler, { ...options, signal: this.abort.signal });
    }
    track(dispose) {
      this.cleanups.push(dispose);
    }
    observer(callback) {
      const observer = new ResizeObserver(callback);
      this.track(() => observer.disconnect());
      return observer;
    }
    frame(callback) {
      const id = requestAnimationFrame(() => {
        this.frames.delete(id);
        if (!this.abort.signal.aborted) callback();
      });
      this.frames.add(id);
    }
    dispose() {
      this.abort.abort();
      for (const id of this.frames) cancelAnimationFrame(id);
      this.frames.clear();
      for (const cleanup of this.cleanups.splice(0)) cleanup();
    }
  };

  // src/webview/inspection/details.ts
  function buildEventDetails(id, text, exceptions) {
    const container = document.createElement("div");
    container.className = "event-details";
    const copy = document.createElement("button");
    copy.className = "copy-button";
    copy.textContent = "Copy event";
    copy.dataset.id = String(id);
    container.append(copy);
    exceptions.forEach((exception, blockIndex) => {
      const section = document.createElement("section");
      section.className = "exception-block";
      const title = document.createElement("strong");
      title.textContent = exception.title;
      const stack = document.createElement("div");
      stack.className = "exception-stack";
      exception.lines.forEach((line, lineIndex) => {
        const element2 = document.createElement(line.source ? "button" : "div");
        element2.textContent = line.text || " ";
        if (line.source) {
          element2.className = "source-link";
          element2.dataset.id = String(id);
          element2.dataset.block = String(blockIndex);
          element2.dataset.line = String(lineIndex);
          element2.title = `Open ${line.source.file}:${line.source.line}`;
        }
        stack.append(element2);
      });
      section.append(title, stack);
      container.append(section);
    });
    const pre = document.createElement("pre");
    pre.textContent = text ?? "Loading\u2026";
    if (exceptions.length) {
      const raw = document.createElement("details");
      const summary = document.createElement("summary");
      summary.textContent = "Original event";
      raw.append(summary, pre);
      container.append(raw);
    } else
      container.append(pre);
    return container;
  }

  // src/webview/inspection/context.ts
  function createInspection(elements, scrollViewport, api, formatTimestamp, scope) {
    let contextAnchor;
    let contextSelected;
    let contextScrollTop = 0;
    let contextEvents = [];
    function showContext(id) {
      contextAnchor = id;
      contextSelected = void 0;
      contextScrollTop = scrollViewport.scrollTop;
      elements.contextStatus.textContent = "Loading\u2026";
      elements.contextLogs.replaceChildren();
      elements.contextDetails.replaceChildren();
      contextEvents = [];
      elements.contextDialog.showModal();
      api.postMessage({ type: "context", id });
    }
    function selectContextEvent(id) {
      contextSelected = id;
      elements.contextDetails.textContent = "Loading\u2026";
      for (const button of elements.contextLogs.querySelectorAll(".context-event")) {
        button.setAttribute("aria-pressed", String(Number(button.dataset.id) === id));
      }
      api.postMessage({ type: "details", id, target: "context" });
    }
    scope.listen(elements.contextClose, "click", () => elements.contextDialog.close());
    scope.listen(elements.contextExport, "click", () => api.postMessage({ type: "exportContext", ids: contextEvents.map((event) => event.id) }));
    scope.listen(elements.contextDialog, "close", () => {
      contextAnchor = void 0;
      contextSelected = void 0;
      elements.contextLogs.replaceChildren();
      elements.contextDetails.replaceChildren();
      contextEvents = [];
      scrollViewport.scrollTop = contextScrollTop;
    });
    scope.listen(elements.contextLogs, "click", (event) => {
      const button = event.target.closest(".context-event");
      if (button)
        selectContextEvent(Number(button.dataset.id));
    });
    scope.listen(elements.contextDetails, "click", handleDetailAction);
    function handleDetailAction(event) {
      const source = event.target.closest(".source-link");
      if (source) {
        api.postMessage({ type: "openSource", id: Number(source.dataset.id), block: Number(source.dataset.block), line: Number(source.dataset.line) });
        return true;
      }
      const copy = event.target.closest(".copy-button");
      if (copy) {
        api.postMessage({ type: "copy", id: Number(copy.dataset.id) });
        return true;
      }
      const context = event.target.closest(".context-button");
      if (context) {
        showContext(Number(context.dataset.id));
        return true;
      }
      return false;
    }
    function receiveContext(data) {
      if (!elements.contextDialog.open || data.id !== contextAnchor)
        return;
      elements.contextStatus.textContent = data.missing ? "This event has been discarded from retained history. Close this view to return to your results." : `${data.server || "Source"} \xB7 Same session \xB7 All levels and captured streams \xB7 Up to 25 retained events before and after \xB7 Snapshot in capture order`;
      contextEvents = data.events ?? [];
      elements.contextLogs.replaceChildren(...data.events.map((event) => {
        const row = document.createElement("tr");
        row.dataset.id = String(event.id);
        row.className = event.id === contextAnchor ? "context-anchor" : "";
        const message = cell("");
        const button = document.createElement("button");
        button.className = "context-event";
        button.dataset.id = String(event.id);
        button.textContent = `${event.id === contextAnchor ? "Selected: " : ""}${event.message ?? ""}${event.truncated ? " [truncated]" : ""}`;
        message.append(button);
        row.append(cell(formatTimestamp(event), "time"), cell(event.level, `level ${event.level}`), message, cell(event.stream, "source"));
        return row;
      }));
      elements.contextLogs.querySelector(".context-anchor")?.scrollIntoView({ block: "center" });
      if (!data.missing)
        selectContextEvent(contextAnchor);
      return;
    }
    function receiveDetails(data) {
      if (elements.contextDialog.open && data.id === contextSelected) elements.contextDetails.replaceChildren(buildEventDetails(data.id, data.text, data.exceptions));
    }
    return { showContext, selectContextEvent, handleDetailAction, receiveContext, receiveDetails };
  }

  // src/webview/popovers.ts
  function createPopovers(scope) {
    const popovers = [];
    function createPopover(container, button, panel) {
      const api = {
        isOpen: () => !panel.hidden,
        close(restoreFocus = false) {
          panel.hidden = true;
          button.setAttribute("aria-expanded", "false");
          if (restoreFocus)
            button.focus();
        },
        open() {
          for (const other of popovers)
            if (other !== api)
              other.close();
          panel.hidden = false;
          button.setAttribute("aria-expanded", "true");
          panel.style.left = "0px";
          panel.style.top = "";
          panel.style.bottom = "";
          panel.style.maxHeight = "";
          panel.style.position = "";
          if (panel.classList.contains("fields-panel") || panel.classList.contains("cheat-sheet") || panel.classList.contains("level-menu") || panel.classList.contains("saved-searches")) {
            const trigger = button.getBoundingClientRect();
            const margin2 = 8;
            const spaceBelow2 = window.innerHeight - trigger.bottom - margin2;
            const spaceAbove2 = trigger.top - margin2;
            const openAbove = spaceBelow2 < 160 && spaceAbove2 > spaceBelow2;
            const maxHeight = Math.max(0, openAbove ? spaceAbove2 : spaceBelow2);
            panel.style.position = "fixed";
            const panelWidth = panel.getBoundingClientRect().width;
            const maxLeft = Math.max(margin2, window.innerWidth - margin2 - panelWidth);
            const preferredLeft = trigger.right - panelWidth;
            panel.style.left = `${Math.max(margin2, Math.min(preferredLeft, maxLeft))}px`;
            panel.style.top = openAbove ? `${margin2}px` : `${trigger.bottom + 4}px`;
            panel.style.bottom = openAbove ? `${window.innerHeight - trigger.top + 4}px` : "";
            panel.style.maxHeight = `${maxHeight}px`;
            return;
          }
          const bounds = panel.getBoundingClientRect();
          if (Number.isFinite(bounds.left) && Number.isFinite(window.innerWidth)) {
            panel.style.left = `${Math.max(14 - bounds.left, Math.min(0, window.innerWidth - 14 - bounds.right))}px`;
          }
          const margin = 8;
          const cap = (value) => Math.max(0, Math.min(value, window.innerHeight * 0.65));
          const spaceBelow = window.innerHeight - bounds.bottom - margin;
          const spaceAbove = button.getBoundingClientRect().top - margin;
          if (spaceBelow < 80 && spaceAbove > spaceBelow) {
            panel.style.top = "";
            panel.style.bottom = "calc(100% + 4px)";
            panel.style.maxHeight = `${cap(spaceAbove)}px`;
          } else {
            panel.style.maxHeight = `${cap(spaceBelow)}px`;
          }
        }
      };
      scope.listen(button, "click", (event) => {
        event.stopPropagation();
        api.isOpen() ? api.close() : api.open();
      });
      popovers.push({ container, ...api });
      return api;
    }
    scope.listen(document, "click", (event) => {
      for (const popover of popovers)
        if (popover.isOpen() && !popover.container.contains(event.target))
          popover.close();
    });
    scope.listen(document, "keydown", (event) => {
      if (event.key !== "Escape")
        return;
      for (const popover of popovers)
        if (popover.isOpen())
          popover.close(true);
    });
    scope.listen(window, "resize", () => {
      for (const popover of popovers)
        popover.close();
    });
    return { popovers, createPopover };
  }

  // src/core/query-completion.ts
  function completionTarget(input) {
    const tokens = [...input.matchAll(/(?:[^\s"]+|"(?:\\.|[^"\\])*"?)+/g)];
    const last = /\s$/.test(input) ? void 0 : tokens.at(-1);
    const text = last?.[0] ?? "";
    const match = text.match(/^(-?)(@?([A-Za-z_][A-Za-z0-9_.]*):)?(.*)$/);
    let value = match[4];
    try {
      if (value.startsWith('"')) value = JSON.parse(value);
    } catch {
      value = value.slice(1);
    }
    return { prefix: input.slice(0, last?.index ?? input.length), negate: match[1], field: match[3], fieldText: match[2], value };
  }
  function completeQuery(input, fields, values) {
    const target = completionTarget(input);
    const prefix = target.prefix + target.negate;
    const options = target.field ? values.map(({ value }) => prefix + target.fieldText + JSON.stringify(value)) : fields.filter((field) => /^[A-Za-z_][A-Za-z0-9_.]*$/.test(field)).map((field) => prefix + field + ":");
    return options.filter((value) => value.length <= 256);
  }

  // src/webview/state.ts
  var LEVELS = ["trace", "debug", "info", "warn", "error", "fatal"];
  var ViewerState = class {
    paused = false;
    following;
    page = 0;
    pages = 1;
    newest = 0;
    before;
    generation;
    lastRows;
    selected;
    selectedDetailText;
    selectedExceptions = [];
    selectedServer;
    selectedSort;
    selectedSortDirection;
    allFields = [];
    columnFields = [];
    extraColumns;
    columnWidths;
    columnOrder;
    hiddenColumns;
    checkedLevels;
    displayTimezone = "local";
    constructor(saved = {}) {
      this.following = !saved.sort;
      this.selectedServer = saved.server ?? "";
      this.selectedSort = saved.sort ?? "";
      this.selectedSortDirection = saved.sortDirection === "asc" ? "asc" : "desc";
      this.extraColumns = Array.isArray(saved.extraColumns) ? saved.extraColumns.filter((field) => typeof field === "string") : [];
      this.columnWidths = saved.columnWidths && typeof saved.columnWidths === "object" ? saved.columnWidths : {};
      this.columnOrder = Array.isArray(saved.columnOrder) ? saved.columnOrder : [];
      this.hiddenColumns = new Set(Array.isArray(saved.hiddenColumns) ? saved.hiddenColumns : []);
      this.checkedLevels = new Set(Array.isArray(saved.levels) ? saved.levels.filter((level) => LEVELS.includes(level)) : LEVELS);
    }
    currentLevels() {
      return this.checkedLevels.size === LEVELS.length ? void 0 : [...this.checkedLevels];
    }
    setFollowing(value) {
      this.following = value;
      this.before = value ? void 0 : this.newest;
    }
    filterChanged() {
      this.page = 0;
      this.lastRows = void 0;
    }
    resetSelection() {
      this.selected = void 0;
      this.selectedDetailText = void 0;
      this.selectedExceptions = [];
    }
    /** Explicit changes close inspection while keeping a fixed history boundary. */
    browseFromInspection() {
      if (!this.paused) return;
      this.paused = false;
      this.resetSelection();
      this.following = false;
      this.before ??= this.newest;
      this.lastRows = void 0;
    }
    resume() {
      this.paused = false;
      this.resetSelection();
      this.selectedSort = "";
      this.filterChanged();
      this.setFollowing(true);
    }
    inspect(id) {
      const opening = this.selected !== id;
      this.resetSelection();
      if (opening) {
        this.selected = id;
        this.paused = true;
        this.before ??= this.newest;
      }
      return opening;
    }
    sort(field) {
      this.selectedSortDirection = this.selectedSort === field && this.selectedSortDirection === "desc" ? "asc" : "desc";
      this.selectedSort = field;
      if (!this.paused) this.setFollowing(false);
      this.filterChanged();
    }
    persist(query) {
      return {
        query,
        levels: [...this.checkedLevels],
        server: this.selectedServer,
        sort: this.selectedSort,
        sortDirection: this.selectedSortDirection,
        columnWidths: this.columnWidths,
        columnOrder: this.columnOrder,
        hiddenColumns: [...this.hiddenColumns],
        extraColumns: this.extraColumns
      };
    }
  };

  // src/webview/search/controls.ts
  function createSearch(elements, state, api, popovers, actions, scope) {
    const { filterChanged } = actions;
    const LEVEL_LABELS = { trace: "Trace", debug: "Debug", info: "Info", warn: "Warn", error: "Error", fatal: "Fatal" };
    function updateLevelButtonLabel() {
      if (state.checkedLevels.size === LEVELS.length)
        elements.levelButton.textContent = "All levels";
      else if (state.checkedLevels.size === 0)
        elements.levelButton.textContent = "No levels";
      else if (state.checkedLevels.size === 1)
        elements.levelButton.textContent = `${LEVEL_LABELS[[...state.checkedLevels][0]]} only`;
      else
        elements.levelButton.textContent = `${state.checkedLevels.size} levels`;
    }
    function setAllLevels(value) {
      state.checkedLevels = value ? new Set(LEVELS) : /* @__PURE__ */ new Set();
      buildLevelMenu();
      updateLevelButtonLabel();
      filterChanged();
    }
    function buildLevelMenu() {
      const actions2 = document.createElement("div");
      actions2.className = "level-actions";
      for (const [label, value] of [["All", true], ["None", false]]) {
        const button = document.createElement("button");
        button.type = "button";
        button.textContent = label;
        scope.listen(button, "click", (event) => {
          event.stopPropagation();
          setAllLevels(value);
        });
        actions2.append(button);
      }
      const labels = LEVELS.map((level) => {
        const label = document.createElement("label");
        const input = document.createElement("input");
        input.type = "checkbox";
        input.checked = state.checkedLevels.has(level);
        scope.listen(input, "change", () => {
          if (input.checked)
            state.checkedLevels.add(level);
          else
            state.checkedLevels.delete(level);
          updateLevelButtonLabel();
          filterChanged();
        });
        label.append(input, document.createTextNode(" " + LEVEL_LABELS[level]));
        return label;
      });
      elements.levelMenu.replaceChildren(actions2, ...labels);
    }
    let savedSearchSignature;
    function renderSearchState(searches) {
      const signature = JSON.stringify(searches.saved ?? []);
      if (signature === savedSearchSignature)
        return;
      savedSearchSignature = signature;
      const makeButton = (item, label, removable = false) => {
        const button = document.createElement("button");
        button.type = "button";
        button.className = "search-item";
        button.textContent = label;
        button.title = item.query || item.serverId || "";
        scope.listen(button, "click", () => {
          elements.search.value = item.query || "";
          state.selectedServer = item.serverId || "";
          state.checkedLevels = new Set(Array.isArray(item.levels) ? item.levels : LEVELS);
          elements.server.value = state.selectedServer;
          buildLevelMenu();
          updateLevelButtonLabel();
          for (const popover of popovers)
            popover.close();
          elements.search.focus();
          state.before = void 0;
          filterChanged();
        });
        if (!removable)
          return button;
        const row = document.createElement("div");
        row.className = "search-item-row";
        row.append(button);
        const remove = document.createElement("button");
        remove.type = "button";
        remove.className = "search-remove";
        remove.textContent = "\xD7";
        remove.title = "Delete saved search";
        remove.setAttribute("aria-label", `Delete saved search: ${item.name}`);
        scope.listen(remove, "click", (event) => {
          event.stopPropagation();
          api.postMessage({ type: "deleteSavedSearch", id: item.id });
        });
        row.append(remove);
        return row;
      };
      const savedItems = (searches.saved ?? []).map((item) => makeButton(item, item.name, true));
      elements.savedSearchList?.replaceChildren(...savedItems.length ? savedItems : [emptyMessage("Save a search to reuse it here.")]);
    }
    function renderAutocomplete(data) {
      if (!elements.fieldSuggestions)
        return;
      elements.fieldSuggestions.replaceChildren(...completeQuery(data.input, data.fields, data.values).map((value) => {
        const option = document.createElement("option");
        option.value = value;
        if (!value.toLowerCase().includes(data.input.toLowerCase())) option.setAttribute("label", data.input);
        return option;
      }));
      elements.search.setAttribute("list", "fieldSuggestions");
    }
    function clearAutocomplete() {
      elements.fieldSuggestions?.replaceChildren();
      elements.search.removeAttribute("list");
    }
    return { updateLevelButtonLabel, buildLevelMenu, renderSearchState, renderAutocomplete, clearAutocomplete };
  }

  // src/webview/table/layout.ts
  function layoutColumnWidths(displayedColumns, columnElements, columnWidths, available, table) {
    if (!columnElements.size)
      return;
    const defaults = { "base:time": 140, "base:level": 110, "base:source": 110 };
    const messageFloor = 300;
    const minWidth = 72;
    const isExplicit = (key) => Number.isFinite(Number(columnWidths[key]));
    const widthFor = (key) => {
      const savedWidth = Number(columnWidths[key]);
      return Number.isFinite(savedWidth) ? Math.max(minWidth, Math.min(1600, savedWidth)) : defaults[key] || 160;
    };
    const fullOtherWidth = displayedColumns.filter((column) => column.key !== "base:message").reduce((sum, column) => sum + widthFor(column.key), 0);
    const sourceElement = columnElements.get("base:source");
    const collapseSource = Boolean(sourceElement) && available > 0 && fullOtherWidth + messageFloor > available;
    if (sourceElement)
      sourceElement.style.visibility = collapseSource ? "collapse" : "";
    const columns = displayedColumns.filter((column) => !(collapseSource && column.key === "base:source"));
    const explicitWidth = columns.filter((column) => isExplicit(column.key)).reduce((sum, column) => sum + widthFor(column.key), 0);
    const autoOthers = columns.filter((column) => column.key !== "base:message" && !isExplicit(column.key));
    const autoOthersNatural = autoOthers.reduce((sum, column) => sum + widthFor(column.key), 0);
    const remaining = available > 0 ? available - explicitWidth : -Infinity;
    let messageWidth;
    let shrinkRatio = 1;
    if (isExplicit("base:message")) {
      messageWidth = widthFor("base:message");
    } else if (remaining >= messageFloor + autoOthersNatural) {
      messageWidth = remaining - autoOthersNatural;
    } else {
      messageWidth = messageFloor;
      const minTotal = autoOthers.length * minWidth;
      const remainingForOthers = remaining - messageFloor;
      shrinkRatio = remainingForOthers > minTotal && autoOthersNatural > minTotal ? (remainingForOthers - minTotal) / (autoOthersNatural - minTotal) : 0;
    }
    const widths = /* @__PURE__ */ new Map();
    let total = 0;
    for (const { key } of columns) {
      const width = key === "base:message" ? messageWidth : isExplicit(key) ? widthFor(key) : Math.round(minWidth + (widthFor(key) - minWidth) * shrinkRatio);
      widths.set(key, width);
      total += width;
    }
    if (available > total && widths.has("base:message")) {
      widths.set("base:message", widths.get("base:message") + available - total);
      total = available;
    }
    for (const [key, width] of widths)
      columnElements.get(key).style.width = `${width}px`;
    table.style.width = `${Math.max(total, available)}px`;
  }

  // src/webview/table/rows.ts
  function createRows(state, columns, formatTimestamp) {
    function buildRow(event) {
      const row = document.createElement("tr");
      row.className = "event-row";
      row.dataset.id = String(event.id);
      const messageCell = cell("");
      const messageContent = document.createElement("div");
      messageContent.className = "message-content";
      const button = document.createElement("button");
      button.className = "message-button";
      button.textContent = `${event.message}${event.truncated ? " [truncated]" : ""}`;
      button.title = event.message ?? "";
      button.setAttribute("aria-expanded", String(event.id === state.selected));
      messageContent.append(button);
      messageCell.append(messageContent);
      for (const column of columns()) {
        let tableCell;
        if (column.key === "base:time")
          tableCell = cell(formatTimestamp(event), "time");
        else if (column.key === "base:level")
          tableCell = cell(event.level, `level ${event.level}`);
        else if (column.key === "base:message")
          tableCell = messageCell;
        else if (column.key === "base:source")
          tableCell = cell(event.stream, "source");
        else
          tableCell = cell(event.fields?.[column.label] ?? "");
        tableCell.dataset.column = column.key;
        row.append(tableCell);
      }
      return row;
    }
    function buildDetailRow(event) {
      const details = document.createElement("tr");
      details.className = "detail-row";
      const container = cell("", "detail-cell");
      container.colSpan = columns().length;
      const actions = document.createElement("div");
      actions.className = "detail-actions";
      const context = document.createElement("button");
      context.textContent = "Show context";
      context.className = "context-button";
      context.dataset.id = String(event.id);
      actions.append(context);
      container.append(actions, buildEventDetails(event.id, state.selectedDetailText, state.selectedExceptions));
      details.append(container);
      return details;
    }
    return { buildRow, buildDetailRow };
  }

  // src/webview/table/controller.ts
  function createTable(elements, scrollViewport, state, api, formatTimestamp, actions, scope) {
    const { request, saveState, updateFollowControl, updateModeLabel } = actions;
    function totalColumnCount() {
      return displayedColumns.length;
    }
    const { buildRow, buildDetailRow } = createRows(state, () => displayedColumns, formatTimestamp);
    let virtualEvents = [];
    let rowHeight = 30;
    let rowHeightMeasured = false;
    let topSpacer;
    let bottomSpacer;
    let expandedHeight = 0;
    let expandedRow;
    let renderRevision = 0;
    let renderedWindow;
    const detailResizeObserver = scope.observer(() => scheduleRenderWindow());
    function ensureSpacers() {
      if (topSpacer)
        return;
      topSpacer = document.createElement("tr");
      topSpacer.className = "virtual-spacer";
      topSpacer.append(document.createElement("td"));
      bottomSpacer = document.createElement("tr");
      bottomSpacer.className = "virtual-spacer";
      bottomSpacer.append(document.createElement("td"));
    }
    function ensureRowHeight() {
      if (rowHeightMeasured)
        return;
      const probe = buildRow({ id: -1, timestamp: "00:00:00.000", message: "sample", level: "info", stream: "", fields: {} });
      probe.style.visibility = "hidden";
      elements.logs.append(probe);
      const measured = probe.getBoundingClientRect().height;
      probe.remove();
      if (measured > 0) {
        rowHeight = measured;
        rowHeightMeasured = true;
      }
    }
    function renderWindow() {
      ensureSpacers();
      ensureRowHeight();
      const total = virtualEvents.length;
      const selectedIndex = virtualEvents.findIndex((event) => event.id === state.selected);
      if (selectedIndex < 0)
        expandedHeight = 0;
      else {
        const detail = elements.logs.querySelector(".detail-row");
        if (detail)
          expandedHeight = detail.getBoundingClientRect().height;
      }
      const overscan = 8;
      const visibleCount = Math.max(1, Math.ceil(scrollViewport.clientHeight / rowHeight)) + overscan * 2;
      const detailTop = (selectedIndex + 1) * rowHeight;
      const offset = selectedIndex >= 0 && scrollViewport.scrollTop > detailTop ? scrollViewport.scrollTop - Math.min(expandedHeight, scrollViewport.scrollTop - detailTop) : scrollViewport.scrollTop;
      let start = Math.floor(offset / rowHeight) - overscan;
      start = Math.max(0, Math.min(start, Math.max(0, total - visibleCount)));
      const end = Math.min(total, start + visibleCount);
      const totalCols = totalColumnCount();
      topSpacer.firstChild.colSpan = totalCols;
      topSpacer.firstChild.style.height = `${start * rowHeight + (selectedIndex >= 0 && selectedIndex < start ? expandedHeight : 0)}px`;
      bottomSpacer.firstChild.colSpan = totalCols;
      bottomSpacer.firstChild.style.height = `${(total - end) * rowHeight + (selectedIndex >= end ? expandedHeight : 0)}px`;
      const windowKey = `${start}:${end}:${renderRevision}`;
      if (renderedWindow === windowKey)
        return;
      renderedWindow = windowKey;
      const focused = document.activeElement;
      const focusedRow = !!focused && elements.logs.contains(focused) ? focused.closest("tr") : void 0;
      const refocusId = focusedRow?.classList.contains("event-row") ? focusedRow.dataset.id : void 0;
      const detailScrollers = [...expandedRow?.querySelectorAll(".event-details, pre") ?? []].map((element2) => ({ element: element2, top: element2.scrollTop, left: element2.scrollLeft }));
      const fragment = document.createDocumentFragment();
      for (let i = start; i < end; i++) {
        const event = virtualEvents[i];
        fragment.append(buildRow(event));
        if (event.id === state.selected) {
          if (!expandedRow) {
            detailResizeObserver.disconnect();
            expandedRow = buildDetailRow(event);
            detailResizeObserver.observe(expandedRow);
          }
          expandedRow.firstChild.colSpan = totalCols;
          fragment.append(expandedRow);
        }
      }
      elements.logs.replaceChildren(topSpacer, fragment, bottomSpacer);
      for (const { element: element2, top, left } of detailScrollers) {
        element2.scrollTop = top;
        element2.scrollLeft = left;
      }
      if (focused && !!focused && elements.logs.contains(focused))
        focused.focus({ preventScroll: true });
      else if (refocusId !== void 0)
        elements.logs.querySelector(`tr.event-row[data-id="${refocusId}"] .message-button`)?.focus({ preventScroll: true });
      const measured = elements.logs.querySelector(".detail-row")?.getBoundingClientRect().height;
      if (measured !== void 0 && measured !== expandedHeight) {
        expandedHeight = measured;
        scheduleRenderWindow();
      }
    }
    let windowRenderQueued = false;
    let followTailRequested = false;
    function scheduleRenderWindow(followTail = false) {
      followTailRequested ||= followTail === true;
      if (windowRenderQueued)
        return;
      windowRenderQueued = true;
      scope.frame(() => {
        windowRenderQueued = false;
        const followTail2 = followTailRequested;
        followTailRequested = false;
        renderWindow();
        if (followTail2 && state.following && !state.paused && !state.selectedSort) {
          scrollViewport.scrollTop = scrollViewport.scrollHeight;
          renderWindow();
        }
      });
    }
    scope.listen(scrollViewport, "scroll", () => scheduleRenderWindow());
    scope.observer(() => {
      rowHeightMeasured = false;
      renderRevision++;
      layoutColumns();
      scheduleRenderWindow(state.following && !state.paused && !state.selectedSort);
    }).observe(scrollViewport);
    function renderRows(events) {
      virtualEvents = events;
      renderRevision++;
      renderWindow();
      if (state.following && !state.paused && !state.selectedSort) {
        scrollViewport.scrollTop = scrollViewport.scrollHeight;
        renderWindow();
        scheduleRenderWindow(true);
      }
    }
    let currentColumns = [];
    const baseColumns = [
      { key: "base:time", label: "Time" },
      { key: "base:level", label: "Level" },
      { key: "base:message", label: "Message" },
      { key: "base:source", label: "Source" }
    ];
    let displayedColumns = [...baseColumns];
    let availableColumns = [];
    let automaticColumns = [];
    let automaticColumnsLocked = false;
    let draggedColumn;
    let columnsInitialized = false;
    let columnElements = /* @__PURE__ */ new Map();
    function updateColumns(columns, force = false) {
      const detected = Array.isArray(columns) ? columns : [];
      if (!automaticColumnsLocked)
        automaticColumns = detected;
      const next = [.../* @__PURE__ */ new Set([...automaticColumns, ...state.extraColumns.filter((field) => state.columnFields.includes(field))])];
      if (columnsInitialized && !force && JSON.stringify(next) === JSON.stringify(availableColumns))
        return;
      columnsInitialized = true;
      renderRevision++;
      availableColumns = next;
      currentColumns = next.filter((label) => !state.hiddenColumns.has(`field:${label}`));
      const allColumns = [...baseColumns, ...currentColumns.map((label) => ({ key: `field:${label}`, label }))];
      const known = new Map(allColumns.map((column) => [column.key, column]));
      displayedColumns = [...state.columnOrder.map((key) => known.get(key)).filter((column) => Boolean(column)), ...allColumns.filter((column) => !state.columnOrder.includes(column.key))];
      state.columnOrder = displayedColumns.map((column) => column.key);
      columnElements = new Map(displayedColumns.map((column) => [column.key, document.createElement("col")]));
      element("eventColumns").replaceChildren(...columnElements.values());
      layoutColumns();
      const head = element("head-row");
      head.replaceChildren(...displayedColumns.map((column) => {
        const { key, label } = column;
        const th = document.createElement("th");
        const grip = document.createElement("span");
        grip.className = "column-grip";
        grip.textContent = "\u283F";
        grip.title = `Drag to move ${label}`;
        grip.draggable = true;
        th.append(grip);
        const sortButton = document.createElement("button");
        sortButton.type = "button";
        sortButton.className = "column-sort";
        const labelText = document.createElement("span");
        labelText.className = "column-label";
        labelText.textContent = label;
        sortButton.append(labelText);
        const sortKey = key === "base:time" ? "timestampMs" : key === "base:level" ? "level" : key === "base:message" ? "message" : key === "base:source" ? "stream" : label;
        const indicator = document.createElement("span");
        indicator.className = "sort-indicator";
        indicator.textContent = state.selectedSort === sortKey ? state.selectedSortDirection === "asc" ? "\u2191" : "\u2193" : "\u2195";
        indicator.setAttribute("aria-hidden", "true");
        sortButton.append(indicator);
        th.append(sortButton);
        th.setAttribute("aria-sort", state.selectedSort === sortKey ? state.selectedSortDirection === "asc" ? "ascending" : "descending" : "none");
        sortButton.title = `Sort by ${label}${state.selectedSort === sortKey ? state.selectedSortDirection === "asc" ? " descending" : " ascending" : ""}`;
        sortButton.setAttribute("aria-label", sortButton.title);
        th.dataset.column = key;
        scope.listen(sortButton, "click", () => {
          state.sort(sortKey);
          updateModeLabel();
          saveState();
          updateColumns(automaticColumns, true);
          updateModeLabel();
          request(true);
          scrollViewport.scrollTop = 0;
          head.querySelectorAll(".column-sort")[displayedColumns.findIndex((column2) => column2.key === key)]?.focus();
        });
        scope.listen(grip, "dragstart", (event) => {
          draggedColumn = key;
          th.classList.add?.("column-dragging");
          event.dataTransfer?.setData("text/plain", key);
          if (event.dataTransfer)
            event.dataTransfer.effectAllowed = "move";
        });
        scope.listen(th, "dragover", (event) => {
          if (draggedColumn && draggedColumn !== key) {
            event.preventDefault();
            th.classList.add("column-drop-target");
          }
        });
        scope.listen(th, "dragleave", () => th.classList.remove?.("column-drop-target"));
        scope.listen(th, "drop", (event) => {
          event.preventDefault();
          th.classList.remove?.("column-drop-target");
          const source = draggedColumn || event.dataTransfer?.getData("text/plain");
          if (!source || source === key)
            return;
          const order = displayedColumns.map((item) => item.key);
          const from = order.indexOf(source);
          const to = order.indexOf(key);
          if (from < 0 || to < 0)
            return;
          order.splice(from, 1);
          order.splice(to, 0, source);
          state.columnOrder = order;
          saveState();
          updateColumns(automaticColumns, true);
          renderWindow();
        });
        scope.listen(grip, "dragend", () => {
          draggedColumn = void 0;
          th.classList.remove?.("column-dragging", "column-drop-target");
          for (const item of head.querySelectorAll?.(".column-drop-target") ?? [])
            item.classList.remove?.("column-drop-target");
        });
        const handle = document.createElement("span");
        handle.className = "resize-handle";
        handle.dataset.column = key;
        handle.setAttribute("aria-label", `Resize ${label} column`);
        handle.title = `Drag to resize ${label}`;
        handle.draggable = false;
        scope.listen(handle, "pointerdown", (event) => {
          event.stopPropagation?.();
          resizeFromPointer(event, key, th);
        });
        scope.listen(handle, "click", (event) => event.stopPropagation?.());
        th.append(handle);
        if (key.startsWith("field:")) {
          const remove = document.createElement("button");
          remove.type = "button";
          remove.className = "remove-column";
          remove.textContent = "\xD7";
          remove.title = `Remove ${label} column`;
          remove.setAttribute("aria-label", `Remove ${label} column`);
          scope.listen(remove, "click", (event) => {
            event.stopPropagation?.();
            state.hiddenColumns.add(key);
            state.columnOrder = state.columnOrder.filter((item) => item !== key);
            saveState();
            updateColumns(automaticColumns, true);
            renderWindow();
          });
          th.append(remove);
        }
        return th;
      }));
      renderFieldList();
      state.lastRows = void 0;
    }
    function resetAutomaticColumns() {
      automaticColumns = [];
      automaticColumnsLocked = false;
    }
    function lockAutomaticColumns() {
      if (automaticColumns.length) automaticColumnsLocked = true;
    }
    function layoutColumns() {
      layoutColumnWidths(displayedColumns, columnElements, state.columnWidths, scrollViewport.clientWidth || 0, element("eventsTable"));
    }
    function resizeFromPointer(event, key, header) {
      if (event.button !== void 0 && event.button !== 0)
        return;
      event.currentTarget?.setPointerCapture?.(event.pointerId);
      const startX = event.clientX;
      const startWidth = header.getBoundingClientRect().width || Number(state.columnWidths[key]) || 80;
      const move = (pointer) => {
        const width = Math.max(72, Math.min(1600, startWidth + pointer.clientX - startX));
        state.columnWidths[key] = Math.round(width);
        layoutColumns();
      };
      const finish = () => {
        document.removeEventListener?.("pointermove", move);
        document.removeEventListener?.("pointerup", finish);
        document.removeEventListener?.("pointercancel", finish);
        saveState();
      };
      scope.listen(document, "pointermove", move);
      scope.listen(document, "pointerup", finish, { once: true });
      scope.listen(document, "pointercancel", finish, { once: true });
      event.preventDefault?.();
      event.stopPropagation?.();
    }
    let fieldListSignature;
    let fieldChoiceOrder = [];
    function fieldChoices() {
      const available = /* @__PURE__ */ new Set([...availableColumns, ...state.columnFields]);
      const known = new Set(fieldChoiceOrder);
      fieldChoiceOrder = [
        ...fieldChoiceOrder.filter((field) => available.has(field)),
        ...[...available].filter((field) => !known.has(field))
      ];
      return fieldChoiceOrder;
    }
    function setAllFields(visible) {
      const choices = fieldChoices();
      for (const label of choices) {
        const key = `field:${label}`;
        if (visible) {
          state.hiddenColumns.delete(key);
          if (!state.extraColumns.includes(label))
            state.extraColumns.push(label);
        } else {
          state.hiddenColumns.add(key);
          state.extraColumns = state.extraColumns.filter((field) => field !== label);
        }
      }
      saveState();
      updateColumns(automaticColumns, true);
      renderWindow();
      request(true);
    }
    scope.listen(elements.fieldsAll, "click", () => setAllFields(true));
    scope.listen(elements.fieldsNone, "click", () => setAllFields(false));
    function renderFieldList() {
      if (!elements.fieldList)
        return;
      const choices = fieldChoices();
      elements.fieldsAll.disabled = !choices.length || choices.every((label) => currentColumns.includes(label));
      elements.fieldsNone.disabled = !choices.length || choices.every((label) => !currentColumns.includes(label));
      const signature = JSON.stringify([choices, currentColumns]);
      if (signature === fieldListSignature)
        return;
      fieldListSignature = signature;
      if (!choices.length) {
        elements.fieldList.replaceChildren(emptyMessage("Additional fields will appear when structured logs are received."));
        return;
      }
      elements.fieldList.replaceChildren(...choices.map((label) => {
        const row = document.createElement("label");
        row.className = "field-toggle";
        row.dataset.field = label;
        const input = document.createElement("input");
        input.type = "checkbox";
        input.checked = currentColumns.includes(label);
        scope.listen(input, "change", () => {
          const key = `field:${label}`;
          if (input.checked) {
            state.hiddenColumns.delete(key);
            if (!state.extraColumns.includes(label))
              state.extraColumns.push(label);
          } else {
            state.hiddenColumns.add(key);
            state.extraColumns = state.extraColumns.filter((field) => field !== label);
          }
          saveState();
          updateColumns(automaticColumns, true);
          renderWindow();
          request(true);
        });
        row.append(input, document.createTextNode(label));
        return row;
      }));
    }
    function toggleExpand(id) {
      const oldRow = elements.logs.querySelector(`tr.event-row[data-id="${id}"]`);
      const viewportTop = scrollViewport.getBoundingClientRect().top;
      const oldTop = oldRow?.getBoundingClientRect().top;
      const rowOffset = oldTop === void 0 ? void 0 : oldTop - viewportTop;
      expandedHeight = 0;
      expandedRow = void 0;
      detailResizeObserver.disconnect();
      renderRevision++;
      if (state.inspect(id)) api.postMessage({ type: "details", id });
      updateFollowControl();
      updateModeLabel();
      renderWindow();
      if (rowOffset !== void 0 && Number.isFinite(rowOffset)) {
        const newTop = elements.logs.querySelector(`tr.event-row[data-id="${id}"]`)?.getBoundingClientRect().top;
        if (newTop !== void 0 && Number.isFinite(newTop))
          scrollViewport.scrollTop += newTop - viewportTop - rowOffset;
      }
    }
    function resetDetails() {
      expandedHeight = 0;
      expandedRow = void 0;
      detailResizeObserver.disconnect();
      renderRevision++;
    }
    function receiveDetails(data) {
      if (data.id !== state.selected) return;
      state.selectedDetailText = data.text;
      state.selectedExceptions = data.exceptions;
      resetDetails();
      renderWindow();
    }
    return {
      updateColumns,
      resetAutomaticColumns,
      lockAutomaticColumns,
      layoutColumns,
      renderFieldList,
      renderRows,
      renderWindow,
      scheduleRenderWindow,
      toggleExpand,
      resetDetails,
      receiveDetails,
      get currentColumns() {
        return currentColumns;
      },
      get automaticColumns() {
        return automaticColumns;
      },
      get events() {
        return virtualEvents;
      },
      get expandedHeight() {
        return expandedHeight;
      }
    };
  }

  // src/webview/time.ts
  function createTimestampFormatter(state) {
    let cachedFormatter;
    let cachedFormatterTimezone;
    function timestampFormatter() {
      if (cachedFormatter !== void 0 && cachedFormatterTimezone === state.displayTimezone)
        return cachedFormatter;
      const options = { hour: "2-digit", minute: "2-digit", second: "2-digit", fractionalSecondDigits: 3, hour12: false };
      if (state.displayTimezone === "utc")
        options.timeZone = "UTC";
      else if (state.displayTimezone && state.displayTimezone !== "local")
        options.timeZone = state.displayTimezone;
      try {
        cachedFormatter = new Intl.DateTimeFormat(void 0, options);
      } catch {
        cachedFormatter = null;
      }
      cachedFormatterTimezone = state.displayTimezone;
      return cachedFormatter;
    }
    function formatTimestamp(event) {
      if (!Number.isFinite(event.timestampMs))
        return event.timestamp;
      const formatter = timestampFormatter();
      return formatter ? formatter.format(event.timestampMs) : event.timestamp;
    }
    return formatTimestamp;
  }

  // src/webview/viewer.ts
  function createViewer(api) {
    const scope = new EventScope();
    const elements = getElements();
    const scrollViewport = document.querySelector(".table-scroll");
    const saved = api.getState() ?? {};
    const state = new ViewerState(saved);
    elements.search.value = saved.query ?? "";
    const bridge = new SnapshotBridge(api, state, () => elements.search.value);
    const request = (force = false) => bridge.request(force);
    const { popovers, createPopover } = createPopovers(scope);
    const formatTimestamp = createTimestampFormatter(state);
    const analysis = createAnalysis(elements, state);
    const inspection = createInspection(elements, scrollViewport, api, formatTimestamp, scope);
    const search = createSearch(elements, state, api, popovers, { filterChanged }, scope);
    const table = createTable(
      elements,
      scrollViewport,
      state,
      api,
      formatTimestamp,
      { request: requestInteraction, saveState, filterChanged, setFollowing, updateFollowControl, updateModeLabel },
      scope
    );
    let serverSignature = "";
    let searchDebounce;
    let autocompleteDebounce;
    let copyFeedbackTimer;
    let cellFilterQuery;
    let minimumSnapshotGeneration = 0;
    const onMessage = (event) => receive(event.data);
    scope.listen(window, "message", onMessage);
    function receive(data) {
      if (data.type === "update") {
        request();
        return;
      }
      if (data.type === "serversChanged") {
        serverSignature = "";
        request(true);
        return;
      }
      if (data.type === "context") {
        inspection.receiveContext(data);
        return;
      }
      if (data.type === "details") {
        if (data.target === "context") inspection.receiveDetails(data);
        else table.receiveDetails(data);
        return;
      }
      if (data.type === "autocomplete") {
        if (data.input !== elements.search.value || (data.serverId ?? "") !== state.selectedServer) return;
        if (elements.search.value.trim()) search.renderAutocomplete(data);
        else search.clearAutocomplete();
        return;
      }
      if (data.type === "analysis") {
        elements.analysisStatus.textContent = "Analysis of the current retained filter";
        analysis.renderAnalysis(data.analysis);
        return;
      }
      if (data.type === "searches") {
        search.renderSearchState(data.searches);
        return;
      }
      if (data.type !== "snapshot")
        return;
      bridge.received();
      if (data.generation < minimumSnapshotGeneration) {
        bridge.flush();
        return;
      }
      minimumSnapshotGeneration = 0;
      if (state.generation !== void 0 && state.generation !== data.generation) {
        state.before = void 0;
        state.page = 0;
        state.lastRows = void 0;
        state.selected = void 0;
        state.selectedDetailText = void 0;
        state.selectedExceptions = [];
        table.resetDetails();
        table.resetAutomaticColumns();
        table.renderRows([]);
        bridge.refreshRequested = true;
      }
      state.generation = data.generation;
      if (data.timezone && data.timezone !== state.displayTimezone) {
        state.displayTimezone = data.timezone;
        state.lastRows = void 0;
      }
      state.newest = data.newest;
      if (!state.following && state.before === void 0)
        state.before = state.newest;
      elements.status.textContent = data.status;
      elements.command.textContent = data.command;
      elements.command.title = data.command;
      elements.stop.disabled = !data.running;
      elements.stop.textContent = state.selectedServer ? "Stop server" : "Stop all";
      const activeSessions = Array.isArray(data.sessions) ? data.sessions.filter((session) => ["running", "stopping"].includes(session.status)) : [];
      elements.sessions.textContent = activeSessions.length ? `${activeSessions.length} active session${activeSessions.length === 1 ? "" : "s"}` : "No active sessions";
      if (data.servers) {
        const signature = JSON.stringify(data.servers.map((server) => [
          server.id,
          server.label,
          server.status,
          server.activeSessions,
          server.taskName,
          server.taskType,
          server.dependencies,
          server.dependencyState,
          server.exitReason
        ]));
        if (signature !== serverSignature) {
          serverSignature = signature;
          const activeCount = data.servers.reduce((sum, server) => sum + (server.activeSessions || 0), 0);
          const options = [document.createElement("option"), ...data.servers.map(() => document.createElement("option"))];
          options[0].textContent = activeCount ? `All servers \xB7 ${activeCount} active` : "All servers";
          options[0].value = "";
          data.servers.forEach((server, index) => {
            const state2 = server.status === "idle" ? "" : ` \xB7 ${server.status}`;
            const activity = server.activeSessions > 1 ? ` (${server.activeSessions} active)` : "";
            const task = server.taskName ? `Task: ${server.taskName}` : server.label;
            const type = server.taskType ? ` (${server.taskType})` : "";
            const dependency = server.dependencies?.length ? ` \xB7 deps ${server.dependencies.join(", ")} (${server.dependencyState || "unknown"})` : server.dependencyState && server.dependencyState !== "none" ? ` \xB7 deps ${server.dependencyState}` : "";
            const reason = server.exitReason ? ` \xB7 ${server.exitReason}` : "";
            options[index + 1].textContent = `${task}${type}${state2}${activity}${dependency}${reason}`;
            options[index + 1].value = server.id;
            options[index + 1].title = [
              server.lastSession ? `Session ${server.lastSession}` : void 0,
              server.taskName ? `Task ${server.taskName}${server.taskType ? ` (${server.taskType})` : ""}` : void 0,
              server.dependencyState ? `Dependencies: ${server.dependencies?.join(", ") || "none"} (${server.dependencyState})` : void 0,
              server.exitReason ? `Exit: ${server.exitReason}` : void 0
            ].filter(Boolean).join(" \xB7 ") || server.status;
          });
          elements.server.replaceChildren(...options);
          elements.server.value = data.servers.some((server) => server.id === state.selectedServer) ? state.selectedServer : "";
          state.selectedServer = elements.server.value;
        }
      }
      const number = (value) => value.toLocaleString();
      const budget = Number.isFinite(data.maxBytes) ? (data.maxBytes / 1048576).toFixed(0) : "?";
      elements.counts.textContent = `${number(data.total)} received \xB7 ${number(data.retained)} retained \xB7 ${number(data.discarded)} discarded \xB7 ${(data.bytes / 1048576).toFixed(1)} / ${budget} MiB \xB7 ${data.truncated} truncated` + (data.persistDropped ? ` \xB7 ${number(data.persistDropped)} disk writes skipped` : "");
      updateModeLabel();
      if (Array.isArray(data.columnFields))
        state.columnFields = data.columnFields;
      table.updateColumns(data.columns ?? []);
      if (data.events?.length)
        table.lockAutomaticColumns();
      table.renderFieldList();
      if (Array.isArray(data.fields))
        state.allFields = data.fields;
      if (data.searches)
        search.renderSearchState(data.searches);
      if (data.events && !bridge.refreshRequested && !state.paused) {
        state.page = data.page ?? 0;
        state.pages = data.pages ?? 1;
        elements.page.textContent = `Page ${state.page + 1} of ${state.pages} \xB7 ${number(data.matched ?? 0)} matches`;
        elements.older.disabled = state.page >= state.pages - 1;
        elements.newer.disabled = state.page === 0;
        const signature = data.events.map((event) => event.id).join(",");
        if (signature !== state.lastRows) {
          state.lastRows = signature;
          table.renderRows(data.events);
        }
        elements.empty.hidden = data.events.length > 0;
        elements.empty.textContent = data.total ? "No matching events in retained history." : "Run a server command to see its logs here.";
        if (state.following && !state.paused && !state.selectedSort)
          table.scheduleRenderWindow(true);
      }
      bridge.flush();
    }
    function updateFollowControl() {
      if (state.paused) {
        elements.follow.setAttribute("aria-pressed", "false");
        elements.follow.setAttribute("aria-label", "Resume live updates");
        elements.follow.title = "Resume live updates";
        elements.follow.textContent = "Resume";
        return;
      }
      elements.follow.setAttribute("aria-pressed", String(state.following));
      elements.follow.setAttribute("aria-label", state.following ? "Live updates" : "Browse retained history");
      elements.follow.title = state.following ? "Live updates" : "Browse retained history";
      elements.follow.textContent = state.following ? "Live" : "Browse";
    }
    function updateModeLabel() {
      elements.older.textContent = state.selectedSort ? "Next \u2192" : "\u2190 Older";
      elements.newer.textContent = state.selectedSort ? "\u2190 Previous" : "Newer \u2192";
      elements.mode.textContent = state.paused ? "Paused \u2014 collection continues" : state.selectedSort ? `Sorted ${state.selectedSortDirection === "asc" ? "ascending" : "descending"}${state.following ? " \xB7 Live updates" : ""}` : state.following ? "Live \xB7 newest 1,000" : "Browsing retained history";
      elements.mode.className = state.following && !state.paused ? "live-mode" : "";
    }
    function setFollowing(value) {
      state.setFollowing(value);
      updateFollowControl();
      updateModeLabel();
    }
    function saveState() {
      api.setState(state.persist(elements.search.value));
    }
    function hasActiveFilter() {
      return Boolean(elements.search.value.trim()) || state.checkedLevels.size !== 6 || Boolean(state.selectedServer);
    }
    function updateCopyResultsControl() {
      elements.copyResults.hidden = !hasActiveFilter();
      elements.copyResults.textContent = "Copy results";
    }
    function requestInteraction() {
      if (state.paused) {
        state.browseFromInspection();
        table.resetDetails();
        table.renderWindow();
      }
      updateFollowControl();
      updateModeLabel();
      request(true);
    }
    function filterChanged() {
      state.filterChanged();
      updateCopyResultsControl();
      saveState();
      requestInteraction();
    }
    function filterForCell(id, column) {
      const event = table.events.find((item) => item.id === id);
      if (!event) return;
      const field = column === "base:time" ? "timestamp" : column === "base:level" ? "level" : column === "base:message" ? "message" : column === "base:source" ? "stream" : column.startsWith("field:") ? column.slice("field:".length) : void 0;
      if (!field) return;
      const value = field === "timestamp" ? event.timestamp : field === "level" ? event.level : field === "message" ? event.message : field === "stream" ? event.stream : event.fields?.[field];
      const text = String(value ?? "").trim().replace(/"/g, "");
      if (!text) return;
      const query = /\s/.test(text) ? `${field}:"${text}"` : `${field}:${text}`;
      return { query, label: `Filter ${field}: ${text}` };
    }
    function closeCellFilterMenu() {
      cellFilterQuery = void 0;
      elements.cellFilterMenu.hidden = true;
    }
    scope.listen(elements.logs, "click", (event) => {
      if (inspection.handleDetailAction(event))
        return;
      const button = event.target.closest(".message-button");
      if (!button)
        return;
      table.toggleExpand(Number(button.closest("tr").dataset.id));
    });
    scope.listen(elements.logs, "contextmenu", (event) => {
      const cell2 = event.target.closest("td[data-column]");
      const row = cell2?.closest("tr.event-row");
      const choice = cell2 && row ? filterForCell(Number(row.dataset.id), cell2.dataset.column ?? "") : void 0;
      if (!choice) return;
      event.preventDefault();
      cellFilterQuery = choice.query;
      elements.cellFilterAction.textContent = choice.label;
      elements.cellFilterAction.title = choice.label;
      elements.cellFilterMenu.style.left = `${Math.max(8, event.clientX)}px`;
      elements.cellFilterMenu.style.top = `${Math.max(8, event.clientY)}px`;
      elements.cellFilterMenu.hidden = false;
    });
    scope.listen(elements.cellFilterAction, "click", () => {
      if (!cellFilterQuery) return;
      elements.search.value = [elements.search.value.trim(), cellFilterQuery].filter(Boolean).join(" ");
      closeCellFilterMenu();
      elements.search.focus();
      filterChanged();
    });
    scope.listen(document, "click", (event) => {
      if (!elements.cellFilterMenu.hidden && !elements.cellFilterMenu.contains(event.target))
        closeCellFilterMenu();
    });
    scope.listen(document, "keydown", (event) => {
      if (event.key === "Escape") closeCellFilterMenu();
    });
    scope.listen(elements.search, "input", () => {
      search.clearAutocomplete();
      updateCopyResultsControl();
      clearTimeout(searchDebounce);
      searchDebounce = setTimeout(filterChanged, 150);
      clearTimeout(autocompleteDebounce);
      if (!elements.search.value.trim()) {
        search.clearAutocomplete();
        return;
      }
      autocompleteDebounce = setTimeout(() => {
        api.postMessage({ type: "autocomplete", input: elements.search.value, serverId: state.selectedServer || void 0 });
      }, 150);
    });
    search.buildLevelMenu();
    search.updateLevelButtonLabel();
    updateFollowControl();
    updateModeLabel();
    updateCopyResultsControl();
    createPopover(elements.levelButton.closest(".popover-container"), elements.levelButton, elements.levelMenu);
    createPopover(elements.searchHelp.closest(".popover-container"), elements.searchHelp, elements.searchHelpPanel);
    createPopover(elements.searchTools.closest(".popover-container"), elements.searchTools, elements.searchToolsPanel);
    createPopover(elements.fieldsButton.closest(".popover-container"), elements.fieldsButton, elements.fieldsPanel);
    scope.listen(elements.copyResults, "click", () => {
      if (!hasActiveFilter()) return;
      api.postMessage({ type: "copyFiltered", query: elements.search.value, levels: state.currentLevels(), serverId: state.selectedServer || void 0 });
      elements.copyResults.textContent = "Copied";
      clearTimeout(copyFeedbackTimer);
      copyFeedbackTimer = setTimeout(updateCopyResultsControl, 1200);
    });
    scope.listen(elements.saveSearch, "click", () => {
      for (const popover of popovers)
        popover.close();
      elements.saveSearchName.value = elements.search.value || "";
      elements.saveSearchDialog.showModal();
      elements.saveSearchName.select?.();
    });
    scope.listen(elements.saveSearchCancel, "click", () => elements.saveSearchDialog.close());
    scope.listen(elements.saveSearchForm, "submit", (event) => {
      event.preventDefault();
      const name = elements.saveSearchName.value;
      elements.saveSearchDialog.close();
      api.postMessage({ type: "saveSearch", name, query: elements.search.value, levels: state.currentLevels(), serverId: state.selectedServer || void 0 });
    });
    scope.listen(elements.analyze, "click", () => {
      elements.analysisDialog.showModal();
      elements.analysisStatus.textContent = "Loading analysis\u2026";
      api.postMessage({ type: "analysis", query: elements.search.value, levels: state.currentLevels(), serverId: state.selectedServer || void 0 });
    });
    scope.listen(elements.analysisClose, "click", () => elements.analysisDialog.close());
    scope.listen(elements.server, "change", () => {
      search.clearAutocomplete();
      state.selectedServer = elements.server.value;
      state.page = 0;
      state.lastRows = void 0;
      table.resetAutomaticColumns();
      updateCopyResultsControl();
      saveState();
      requestInteraction();
    });
    scope.listen(elements.follow, "click", () => {
      if (state.paused || !state.following) {
        state.resume();
        table.resetDetails();
        saveState();
        table.updateColumns(table.automaticColumns, true);
        updateFollowControl();
        updateModeLabel();
        request(true);
        table.scheduleRenderWindow(true);
      } else {
        setFollowing(false);
        updateFollowControl();
        request(true);
      }
    });
    scope.listen(elements.older, "click", () => {
      if (state.following && !state.paused)
        setFollowing(false);
      state.page = Math.min(state.pages - 1, state.page + 1);
      requestInteraction();
    });
    scope.listen(elements.newer, "click", () => {
      state.page = Math.max(0, state.page - 1);
      requestInteraction();
    });
    scope.listen(elements.clear, "click", () => {
      state.columnFields = [];
      minimumSnapshotGeneration = Math.max(minimumSnapshotGeneration, (state.generation ?? 0) + 1);
      table.resetAutomaticColumns();
      table.updateColumns([], true);
      table.renderFieldList();
      search.clearAutocomplete();
      state.browseFromInspection();
      table.resetDetails();
      api.postMessage({ type: "clear" });
      requestInteraction();
    });
    scope.listen(elements.stop, "click", () => api.postMessage({ type: "stop", serverId: state.selectedServer || void 0 }));
    scope.listen(elements.config, "click", () => api.postMessage({ type: "config" }));
    scope.listen(elements.manage, "click", () => api.postMessage({ type: "manageServers" }));
    function exportRequest(type) {
      api.postMessage({ type, query: elements.search.value, levels: state.currentLevels(), serverId: state.selectedServer || void 0 });
    }
    scope.listen(elements.export, "click", () => exportRequest("export"));
    scope.listen(elements.import, "click", () => api.postMessage({ type: "import" }));
    scope.listen(elements.run, "click", () => api.postMessage({ type: "run", serverId: elements.server.value || void 0 }));
    scope.listen(document, "visibilitychange", () => {
      if (!document.hidden)
        request();
    });
    const fallbackTimer = setInterval(() => request(), 5e3);
    request();
    return {
      state,
      bridge,
      table,
      search,
      inspection,
      receive,
      dispose() {
        scope.dispose();
        clearInterval(fallbackTimer);
        clearTimeout(searchDebounce);
        clearTimeout(autocompleteDebounce);
        clearTimeout(copyFeedbackTimer);
        window.removeEventListener("message", onMessage);
      }
    };
  }

  // src/webview/main.ts
  createViewer(acquireVsCodeApi());
})();
