import { build, context } from 'esbuild';
import { spawn, spawnSync } from 'node:child_process';
import { rmSync } from 'node:fs';

const options = {
  entryPoints: ['src/webview/main.ts'], outfile: 'media/viewer.js', bundle: true,
  platform: 'browser', format: 'iife', target: 'es2022',
  banner: { js: '// Generated by npm run compile from src/webview/main.ts. Do not edit directly.' },
};
const tsc = 'node_modules/typescript/bin/tsc';
if (process.argv.includes('--watch')) {
  const browser = await context(options);
  await browser.watch();
  const host = spawn(process.execPath, [tsc, '--watch', '--preserveWatchOutput'], { stdio: 'inherit' });
  const types = spawn(process.execPath, [tsc, '-p', 'tsconfig.webview.json', '--watch', '--preserveWatchOutput'], { stdio: 'inherit' });
  const stop = async () => { host.kill(); types.kill(); await browser.dispose(); };
  process.once('SIGINT', stop); process.once('SIGTERM', stop);
} else {
  // Removed or moved modules must not linger in the extension package.
  rmSync('out', { recursive: true, force: true });
  const result = spawnSync(process.execPath, [tsc], { stdio: 'inherit' });
  if (result.status !== 0) process.exit(result.status ?? 1);
  const browserTypes = spawnSync(process.execPath, [tsc, '-p', 'tsconfig.webview.json'], { stdio: 'inherit' });
  if (browserTypes.status !== 0) process.exit(browserTypes.status ?? 1);
  await build(options);
}
